name: Deploy Test Application

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - complete

jobs:
  deploy:

    runs-on: ubuntu-22.04
    permissions:
      contents: read
steps:
    uses: actions/checkout@v4
