name: Deploy Test Application

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Deploy AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Studentify \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name Studentify \
            --github-location "repository=${{ github.repository }},commitId=${{ github.sha }}" \
            --description "Studentify"
